### ISSUE TITLE
Error: 80040154:Class not registered

### ISSUE THREAD

**Issue by mousumipaul** [microsoft/Windows-Camera#18]
The exe generated after build does not run in windows 8.1. It gives the following error at runtime:
Error: 80040154:Class not registered

**Comment by LPBourret** [comment]
Hi, yes most projects in this repo are built with a a dependency of at least Windows 10 build version 16299. See the SDK requirement on each sample in their respective readme file.

**Comment by oshuqair** [comment]
I am trying to run the VirtualCameraSample on windows 11 I have the windows SDK 10.0.22000.0 installed but yet am getting Class not registered on virtual camera start call 
 RETURN_IF_FAILED(spVirtualCamera->Start(nullptr));
 
 any hints?

**Comment by LPBourret** [comment]
Hi, yes probably because the vcam is not registered on the system. The sample requires 2 steps: 
- first register the virtual camera on the target system (registering the COM component in the virtual camera dll). This is done by compiling and installing the .msi
- instantiate the virtual camera using an application: the app calls MFCreateVirtualCamera() using the CLSID of the COM component registered in step 1 followed by IMFVirtualCamera::Start())

my hunch is that step 1 is missing in your case resulting in that error
