### ISSUE TITLE
Class not registered

### ISSUE THREAD

**Issue by oshuqair** [microsoft/Windows-Camera#28]
I am trying to run the VirtualCameraSample on windows 11 I have the windows SDK 10.0.22000.0 installed but yet am getting Class not registered on virtual camera start call
RETURN_IF_FAILED(spVirtualCamera->Start(nullptr));

any hints?

**Comment by LPBourret** [comment]
Hi, yes probably because the vcam is not registered on the system. The sample requires 2 steps:

- first register the virtual camera on the target system (registering the COM component in the virtual camera dll). This is done by compiling and installing the .msi
- instantiate the virtual camera using an application: the app calls MFCreateVirtualCamera() using the CLSID of the COM component registered in step 1 followed by IMFVirtualCamera::Start())

my hunch is that step 1 is missing in your case resulting in that error

**Comment by LPBourret** [comment]
closing, reopen if you encounter this issue still
