### ISSUE TITLE
[ExternalCameraSettingsAppSample][DefaultControlHelper] set DefaultValue error with Access is denied

### ISSUE THREAD

**Issue by LiangJy123** [microsoft/Windows-Camera#40]
Hi , 

I try to change default value of brightness , but get a exception:
```
CameraSettingsExternalSettingsApp\DefaultControlHelper\DefaultControlHelper.cpp(128)\DefaultControlHelper_WinRT.dll!00007FFB0DD10FAC: (caller: 00007FFB0DD19FF4) Exception(1) tid(2f9c) 80070005 Access is denied.
    [winrt::DefaultControlHelper::implementation::DefaultController::DefaultValue(strongManager->Save())]



  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

Before I get the exception , I modified the program flow of "ExternalCameraSettingsAppSample" for standalone launching instead of launching from the settings page.

Does "ExternalCameraSettingsAppSample" lost permissions when it doesn't launch from the setting page ?

Thanks.

**Comment by LPBourret** [comment]
Hi,
in order to save default configuration values for a camera from an app, that camera needs to specify that this app is its control app (reading can be done from any app, but writing/saving values is constrained). With this error, I suspect in your case that the camera you are trying to save default configuration values for is not pointing at your app's PFN as per the Readme.md. 
i.e. in your app project in Visual Studio, right click the .csproj, got to "properties" then in the "Application" tab, click the "PackageManifest..." button and navigate to the "Packaging" tab. There you see a greyed out text box labeles "Package Family Name" and the text value in it is your app's PFN.
This PFN should then be set in the registry for your camera in *`HKLM\SYSTEM\CurrentControlSet\Control\DeviceClasses\{e5323777-f976-4f5b-9b55-b94699c46e44}\<camera symlink>\#GLOBAL\Device Parameters`* as a *`REG_SZ`* entry named *`SCSVCamPfn`*

**Comment by LiangJy123** [comment]
Thank you for your detailed guidance .
With your guidance I can save default configuration values now .

But I have another question ,  that  a new app association is not easy to takes effect after updating the registry (`SCSVCamPfn`) .

I mean, after several times of disable/enable camera or restart system , it may takes effect in the system.

Are there any other steps or special flows to do? 

Thanks again.

**Comment by LiangJy123** [comment]
Thanks @LPBourret .

You help me lot. :)
